### PR TITLE
updated to Julia v1.3

### PR DESCRIPTION
**Pull request by bmlindor**

### CODE REVIEW

**Comment by ericagol** [comment]
@bmlindor I like the changes you made, but I would like to preserve the C, Python & IDL versions of the code somewhere.  Since this may turn into a package, maybe the TTVFaster repo should be kept as-is, and the Julia code could be moved to TTVFaster.jl?  (I think @langfzac suggested this yesterday.)

**Review by ericagol — COMMENTED** [review]
Thumbs up.

**Review by ericagol — COMMENTED** [review]
It looks like all of the C/IDL/Python code (& outdated Julia code) has been moved to the deprecated directory.  Maybe we should add a note in the README about where these have been moved in case this causes a compatibility issue for users of the TTVFaster in languages other than Julia.

**Comment by bmlindor** [comment]
I'm planning to close this request and just use the branch that I forked for TTVFaster.jl

**Comment by ericagol** [comment]
(@bmlindor When I left the second comment, I was just replying via email, so I forgot that I had left almost exactly the same comment almost a year ago!)

**Comment by bmlindor** [comment]
thanks for the feedback. I updated some docs on TTVFaster and finally registered it as a package. Now running a test essentially runs through the Kepler62 example and makes sure that there are values returned for the TTVs.

If you think going ahead to modify the LaplaceCoefficients module would improve the results further, let me know.

**Comment by ericagol** [comment]
Great!  Are you planning to detach it to make it its own standalone repository?  I found some info about this on stackoverflow:  https://stackoverflow.com/questions/18390249/github-make-fork-an-own-project

**Comment by ericagol** [comment]
I can't recall what modifications we had discussed for the LaplaceCoefficients module?

**Comment by bmlindor** [comment]
we discussed whether implementing analytic derivatives could speed up the code. this would require computing the derivatives of the Laplace coefficients from Table 1 of Agol & Deck (2015). you also mentioned maybe seeing how the finite differences compared to the analytic method. 

yes, I was looking into that. thanks for the link. detaching complete!

**Pull request closed without merging**
